name = "nodemeld-backend"
main = "src/index.js"
compatibility_date = "2024-01-01"

[[d1_databases]]
binding = "DB"
database_name = "microlaunch_db"
database_id = "818d8759-01d4-4951-92cf-c6771c8bbbad"

[triggers]
crons = ["0 */6 * * *"]

# Set these secrets via: wrangler secret put RESEND_API_KEY
# wrangler secret put GROQ_API_KEY
# wrangler secret put SERPER_API_KEY
